###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

    webserver:
      image: nginx:alpine
      container_name: chessdb-webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "80:80"

    mariadb:
      image: mariadb:10.1
      container_name: chessdb-mariadb
      working_dir: /application
      volumes:
        - .:/application
      environment:
        - MYSQL_ROOT_PASSWORD=password
        - MYSQL_DATABASE=chessdb
        - MYSQL_USER=chessdb
        - MYSQL_PASSWORD=password
      ports:
        - "8083:3306"

    neo4j:
      image: kbastani/docker-neo4j:latest
      container_name: chessdb-neo4j
      working_dir: /application
      volumes:
          - .:/application
          - /opt/data
      ports:
          - "17474:7474"
          - "7687:7687"
      environment:
          NEO4J_AUTH: "none"


    redis:
        image: redis:4.0.5-alpine
        command: ["redis-server", "--appendonly", "yes"]
        hostname: redis
        volumes:
          - /opt/data

    php-fpm:
      build: phpdocker/php-fpm
      container_name: chessdb-php-fpm
      working_dir: /application
      links:            ## connects neo4j to app container
         - neo4j
         - mariadb
         - webserver
         - redis
      volumes:
        - .:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.1/fpm/conf.d/99-overrides.ini

